apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: hbase
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: hbase
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        - --zkquorum=zk-0.zk-ss.hbase.svc.cluster.local:2181,zk-1.zk-ss.hbase.svc.cluster.local:2181,zk-2.zk-ss.hbase.svc.cluster.local:2181
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
